# Puerto dinámico para Railway
server.port=${PORT:8080}

# Conexión flexible: Si Railway detecta Postgres, lo usa. Si no, usa H2 (en tu PC).
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://postgres:sQfujPkTWfvNQCoPqtNBpxvHYnHvOwTY@metro.proxy.rlwy.net:23044/railway}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:sQfujPkTWfvNQCoPqtNBpxvHYnHvOwTY}
#spring.datasource.driver-class-name=${JDBC_DATABASE_DRIVER:org.h2.Driver}

# Hibernate: 'update' crea las tablas si no existen sin borrar los datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger y H2 Console
springdoc.swagger-ui.path=/swagger-ui.html
spring.h2.console.enabled=true
