# 1. Puerto dinámico (Obligatorio para que Railway asigne el puerto)
server.port=${PORT:8080}

# 2. Conexión a Base de Datos
# Railway usa variables de entorno. Estas coinciden con los nombres estándar de Railway.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://metro.proxy.rlwy.net:23044/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sQfujPkTWfvNQCoPqtNBpxvHYnHvOwTY}
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Hibernate y JPA
# 'update' creará las tablas automáticamente al detectar tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Documentación y Utilidades
springdoc.swagger-ui.path=/swagger-ui.html
# Desactivamos H2 console para evitar conflictos en producción con Postgres
spring.h2.console.enabled=false
