# 1. Configuración del Servidor
server.port=${PORT:8080}

# 2. Conexión a la Base de Datos (Usa las variables de IntelliJ/Railway)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configuración de JPA / Hibernate
# Esto ayuda a que Spring entienda que hablas con PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas que hace el programa (útil para el parcial)
spring.jpa.show-sql=true