# 1. Puerto
server.port=8080

# 2. Base de Datos Artificial (En Memoria)
spring.datasource.url=jdbc:h2:mem:db_club
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 3. Hibernate (Crea las tablas solo con darle Run)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. Consola H2 (Para que veas tus tablas en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true